/*
 * generated by Xtext 2.17.1
 */
package circus.robocalc.robosim.textual.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class RoboSimUiModule extends AbstractRoboSimUiModule {
}
